---
openapi: 3.0.3
info:
  title: Quarkus Service API
  description: API surface exposed by the Quarkus service
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://user13-devspaces-maarten-jfokus-test-1-user13-devspaces.apps.cluster-ssghb.ssghb.sandbox512.opentlc.com/
    description: (RHDH component deployment)
  - url: http://localhost:8080/
    description: (localhost testing)
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
